//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.08 at 04:16:07 PM PDT 
//


package entg.util.objrep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import java.sql.*;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Objects"/>
 *         &lt;element ref="{}Parameters"/>
 *         &lt;element ref="{}Metadata"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "objects",
    "parameters",
    "metadata"
})
@XmlRootElement(name = "ObjectRepository")
public class ObjectRepository {

    @XmlElement(name = "Objects", required = true)
    protected Objects objects;
    @XmlElement(name = "Parameters", required = true)
    protected String parameters;
    @XmlElement(name = "Metadata", required = true)
    protected String metadata;

    /**
     * Gets the value of the objects property.
     * 
     * @return
     *     possible object is
     *     {@link Objects }
     *     
     */
    public Objects getObjects() {
        return objects;
    }

    /**
     * Sets the value of the objects property.
     * 
     * @param value
     *     allowed object is
     *     {@link Objects }
     *     
     */
    public void setObjects(Objects value) {
        this.objects = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameters(String value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetadata(String value) {
        this.metadata = value;
    }

    public void insertObjRep(Connection conn, String objrepFile) throws Exception {
    	Statement stmt = conn.createStatement();
    	ResultSet rs = stmt.executeQuery("select entg_qtp_object_rep_s.nextval from dual");
    	rs.next();
    	int repId = rs.getInt(1);
    	stmt.close();
    	
    	PreparedStatement pstmt = conn.prepareStatement(
    			 "insert into entg_qtp_object_rep values (?,?)");
    	pstmt.setInt(1, repId);
    	pstmt.setString(2, objrepFile);
    	pstmt.execute();
    	pstmt.close();
    	this.getObjects().insertObjects(conn, repId);
    }
}
