//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.08 at 04:16:07 PM PDT 
//


package entg.util.objrep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.sql.*;
import java.util.Iterator;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}BasicIdentification"/>
 *         &lt;element ref="{}ChildObjects"/>
 *         &lt;element ref="{}Comments"/>
 *         &lt;element ref="{}LastUpdateTime"/>
 *         &lt;element ref="{}Properties"/>
 *       &lt;/choice>
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Class" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="OracleButton"/>
 *             &lt;enumeration value="OracleCheckbox"/>
 *             &lt;enumeration value="OracleFormWindow"/>
 *             &lt;enumeration value="OracleList"/>
 *             &lt;enumeration value="OracleNavigator"/>
 *             &lt;enumeration value="OracleTabbedRegion"/>
 *             &lt;enumeration value="OracleTable"/>
 *             &lt;enumeration value="OracleTextField"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "basicIdentification",
    "childObjects",
    "comments",
    "lastUpdateTime",
    "properties"
})
@XmlRootElement(name = "Object")
public class Object {

    @XmlElement(name = "BasicIdentification")
    protected BasicIdentification basicIdentification;
    @XmlElement(name = "ChildObjects")
    protected ChildObjects childObjects;
    @XmlElement(name = "Comments")
    protected Comments comments;
    @XmlElement(name = "LastUpdateTime")
    protected LastUpdateTime lastUpdateTime;
    @XmlElement(name = "Properties")
    protected Properties properties;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "Class", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String clazz;

    /**
     * Gets the value of the basicIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link BasicIdentification }
     *     
     */
    public BasicIdentification getBasicIdentification() {
        return basicIdentification;
    }

    /**
     * Sets the value of the basicIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicIdentification }
     *     
     */
    public void setBasicIdentification(BasicIdentification value) {
        this.basicIdentification = value;
    }

    /**
     * Gets the value of the childObjects property.
     * 
     * @return
     *     possible object is
     *     {@link ChildObjects }
     *     
     */
    public ChildObjects getChildObjects() {
        return childObjects;
    }

    /**
     * Sets the value of the childObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChildObjects }
     *     
     */
    public void setChildObjects(ChildObjects value) {
        this.childObjects = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link Comments }
     *     
     */
    public Comments getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comments }
     *     
     */
    public void setComments(Comments value) {
        this.comments = value;
    }

    /**
     * Gets the value of the lastUpdateTime property.
     * 
     * @return
     *     possible object is
     *     {@link LastUpdateTime }
     *     
     */
    public LastUpdateTime getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * Sets the value of the lastUpdateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link LastUpdateTime }
     *     
     */
    public void setLastUpdateTime(LastUpdateTime value) {
        this.lastUpdateTime = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link Properties }
     *     
     */
    public Properties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Properties }
     *     
     */
    public void setProperties(Properties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }
    
    public void insertObject(Connection conn, int repId, int parObjId) throws Exception {
    	Statement stmt = conn.createStatement();
    	ResultSet rs = stmt.executeQuery("select entg_qtp_objects_s.nextval from dual");
    	rs.next();
    	int objId = rs.getInt(1);
    	stmt.close();
    	
    	PreparedStatement pstmt = conn.prepareStatement(
    			 "insert into entg_qtp_objects values (?,?,?,?,?)");
    	pstmt.setInt(1, objId);
    	pstmt.setInt(2, repId);
    	pstmt.setInt(3, parObjId);
    	
    	pstmt.setString(4, this.getName());
    	pstmt.setString(5, this.getClazz());
    	pstmt.execute();
    	pstmt.close();
    	
    	for( Iterator iter = this.getProperties().getProperty().iterator(); iter.hasNext(); ) {
    		Property prop = (Property) iter.next();
    	
    		prop.insertProperty(conn, objId);
    	}
    	
    	for( Iterator iter = this.getChildObjects().getObject().iterator(); iter.hasNext(); ) {
    		Object obj = (Object) iter.next();
    	
    		obj.insertObject(conn, -1,objId);
    	}
    	
    	
    }

}
